CREATE DATABASE SYSEDIDB;

USE SYSEDIDB;

CREATE TABLE EDITORAS(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	EDIID INT,
	EDINOME VARCHAR(50),
	EDISIGLA VARCHAR(25),
	EDIOBSERVACOES VARCHAR(500)
);

CREATE TABLE LIVROS(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	LIVID INT,
	LIVNOME VARCHAR(50),
	LIVANOPUBLICACAO INT,
	LIVISBN DECIMAL(14),
	LIVOBSERVACOES VARCHAR(500),
	EDIID INT
);

CREATE TABLE AUTORES(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	AUTID INT,
	AUTNOME VARCHAR(50),
	AUTPSEUDONIMO VARCHAR(50),
	AUTOBSERVACOES VARCHAR(500),

);
